### ISSUE TITLE
concordance navigator switch concordance

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#108]
due to a faulty css the standard build of EO will be stripped of the capabilities for switching between concordances. The error is:
```CSS
.ediromConcordanceNavigatorWindow .x-window-body > span > div:first-child > div:first-child {
    display: none;
}
```
in `EdiromOnline-all_01.css`:5839
