### ISSUE TITLE
[ftr] add XQunit tests

### ISSUE THREAD

**Issue by peterstadler** [Edirom/Edirom-Online#438]
# Is your feature request related to a problem? Please describe.

The Edirom Online has literally no test system installed which is a huge drawback for all development.

This proposal is to add XQunit tests to the Edirom Online build system and to GitHub actions as a first step towards proper testing.

# Describe the solution you'd like

Yes, I can definitely describe the solution I'd like! The general approach is to:

1. **Install eXist-db in the GitHub Actions runner.**
2. **Run your XQuery unit tests.**
3. **Report the results.**

Here’s a step-by-step guide to integrate XQuery unit tests with GitHub Actions.

### Step 1: Create a GitHub Actions Workflow
Create a new file in your repository at `.github/workflows/ci.yml` (or similar) to define the workflow.

```yaml
name: CI - XQuery Unit Tests

on: [push, pull_request]

jobs:
  xquery-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Download and install eXist-db
      run: |
        curl -L https://github.com/eXist-db/exist/releases/download/eXist-6.2.0/exist-6.2.0.dmg > exist.dmg
        sudo hdiutil attach exist.dmg
        sudo installer -pkg /Volumes/exist-db-6.2.0/eXist-db-6.2.0.pkg -target /
        sudo /usr/local/existdb/bin/startup.sh

    - name: Wait for eXist-db to start
      run: |
        sleep 60
        curl --fail http://localhost:8080/exist || exit 1

    - name: Run XQuery Unit Tests
      run: |
        # Here you can run the XQuery unit tests via eXist-db’s REST API or other methods
        curl --user admin:password --fail --data-binary @tests/my-tests.xq \
        -H "Content-Type: application/xquery" \
        http://localhost:8080/exist/rest/db/my-tests.xq
```

### Step 2: Install and Run eXist-db
- **Download eXist-db:** You can download the latest stable version of eXist-db using `curl`.
- **Install and Start eXist-db:** Depending on the runner environment (Linux, macOS, or Windows), the installation may vary slightly. For Linux/macOS, I have used `.dmg` and `.pkg` in the example, but you may use `.tar.gz` for a more flexible installation.
- **Start eXist-db:** After installation, start the eXist-db server.
- **Wait for the server:** It's important to add a wait time (`sleep`) to ensure the server starts before you run the tests.

### Step 3: Running XQuery Tests
If you are using XQuery Unit (like [XQUnit](https://github.com/xqunit/xqunit)) for your tests, you will need to:
- Place your test files in the eXist-db repository.
- Run them either using eXist-db's REST API (as shown) or any other method that triggers test execution.

You can execute XQuery files by sending them via HTTP POST to the `/rest/db` endpoint as shown in the `curl` command.

### Step 4: Check the Test Results
If the test fails, you want the GitHub Action to fail. If the `curl` request returns a non-success HTTP status (non-2xx), the GitHub Action will fail automatically.

You can modify the test execution step based on your framework and the expected output format of the tests. You might want to further customize how you report and parse the results of these tests.

### Additional Tips:
1. **Parallel Jobs:** You can also run tests in parallel to speed up your CI pipeline.
2. **Artifacts:** If you need to store test results as artifacts, GitHub Actions allows you to upload them.

```yaml
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: xquery-test-results
        path: results/
```

### Example Test Script (XQUnit)
```xquery
xquery version "3.1";

import module namespace xqunit="http://xqunit.org";

xqunit:test-suite("My Test Suite", 
  xqunit:test-case("Sample Test",
    xqunit:assert-equal(2, 1 + 1)
  )
)
```

Once your test framework is in place, this should allow you to run the XQuery unit tests seamlessly in GitHub Actions.

To ensure that your GitHub Actions pipeline fails when your XQuery unit tests return errors, you can follow one of these approaches depending on the structure of your tests and how eXist-db responds to them. You can achieve this by handling the HTTP response from eXist-db and parsing the results to detect failures or errors.

Here’s how you can do this step-by-step:

### Approach 1: Check HTTP Response Status from eXist-db
If your XQuery tests are executed via eXist-db's REST API and the tests return an HTTP response status other than `2xx` (for example, `4xx` or `5xx` for errors), the GitHub Action will automatically fail. 

Here’s the relevant part of the GitHub Actions script that will handle this:

```yaml
    - name: Run XQuery Unit Tests
      run: |
        # Run your XQuery tests
        curl --user admin:password --fail --data-binary @tests/my-tests.xq \
        -H "Content-Type: application/xquery" \
        http://localhost:8080/exist/rest/db/my-tests.xq

        # The --fail flag ensures that if the server returns a 4xx or 5xx status code,
        # the curl command will return a non-zero exit code, causing the action to fail.
```

- The `--fail` option in `curl` will cause the command to exit with an error if an HTTP error (4xx or 5xx) is returned.
- The GitHub Action will stop and fail at this point if the tests do not pass.

### Approach 2: Parse Test Output and Fail on Errors
If the XQuery unit tests output structured results (like XML or JSON), you can check the output for any error indicators and explicitly fail the action.

For example, if your XQuery unit tests produce XML or JSON results, you can analyze the output to find failures. Let’s assume the test output looks like this:

```xml
<tests>
  <test>
    <name>Test 1</name>
    <status>passed</status>
  </test>
  <test>
    <name>Test 2</name>
    <status>failed</status>
  </test>
</tests>
```

You can fetch the output, parse it, and check for any `failed` statuses. If any are found, the action will fail.

1. **Save the output of the tests** (assuming the results are returned in XML).
2. **Parse the XML output** and check for failures.
3. **Use `exit 1`** to fail the action if errors are detected.

Here’s an extended version of the workflow using `xmllint` to parse the results:

```yaml
    - name: Run XQuery Unit Tests and save output
      run: |
        curl --user admin:password --data-binary @tests/my-tests.xq \
        -H "Content-Type: application/xquery" \
        -o results.xml \
        http://localhost:8080/exist/rest/db/my-tests.xq

    - name: Check for test failures
      run: |
        # Parse the XML output and check if any test has failed
        if xmllint --xpath "count(//test[status='failed'])" results.xml | grep -q 0; then
          echo "All tests passed!"
        else
          echo "Test failures found!"
          exit 1
        fi
```

- **Explanation**:
  - The `curl` command saves the output to a file (`results.xml`).
  - `xmllint` is used to parse the XML and count how many `<test>` elements have a `<status>` of `failed`.
  - If any test has failed, the script exits with a non-zero exit code (`exit 1`), which will cause the action to fail.

### Approach 3: Use a Custom XQuery Test Framework with Built-in Error Reporting
If you are using a test framework like [XQUnit](https://github.com/xqunit/xqunit) or a similar XQuery testing framework, many of these tools have built-in error reporting.

For instance, if you use XQUnit, you can modify your GitHub Action to check whether the test suite has passed or failed based on the exit code or the output from the test framework itself.

Example using XQUnit:

1. **Run the tests using XQUnit:**

```xquery
xquery version "3.1";

import module namespace xqunit="http://xqunit.org";

xqunit:test-suite("My Test Suite", 
  xqunit:test-case("Test 1",
    xqunit:assert-equal(2, 1 + 1)
  ),
  xqunit:test-case("Test 2",
    xqunit:assert-equal(2, 2 + 2)  (: This will fail :)
  )
)
```

2. **Run the tests via GitHub Actions:**

```yaml
    - name: Run XQUnit tests
      run: |
        # Run your XQuery unit tests via XQUnit
        curl --user admin:password --data-binary @tests/my-xqunit-tests.xq \
        -H "Content-Type: application/xquery" \
        -o xqunit-results.xml \
        http://localhost:8080/exist/rest/db/my-xqunit-tests.xq

    - name: Parse XQUnit results and fail on errors
      run: |
        # Use xmllint or similar tool to check if any test case failed
        if xmllint --xpath "count(//test-case[@status='fail'])" xqunit-results.xml | grep -q 0; then
          echo "All tests passed!"
        else
          echo "Test failures found!"
          exit 1
        fi
```

### Summary of Key Points
- **`curl --fail`**: This ensures the GitHub action fails if the HTTP status code is 4xx or 5xx.
- **Parsing Test Output**: Use `xmllint`, `grep`, or a similar tool to parse the test results and detect failures.
- **Custom Test Frameworks**: If using a specific XQuery testing framework, leverage its error reporting and parse results accordingly to ensure the action fails on errors.

This approach will allow your GitHub Actions pipeline to fail if your XQuery tests encounter any issues, ensuring robust CI testing for your eXist-db project.

# additional thoughts

In addition to what ChatGGP provided so generously I think we should streamline the ant based build process to include 

1. the build of the artifacts
2. the docker build
3. the testing

So finally, the Github actions (or any other CI/Cd system), too, would not run Docker commands itself but only ant commands for building and testing.
